CREATE TABLE [dbo].[Customers]
(
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[OrganisationID] INT NOT NULL, 
	[Contact Name] NVARCHAR(255) NULL,
	[Display Name] NVARCHAR(255) NULL,
	[Company Name] NVARCHAR(255) NULL,
	[Salutation] NVARCHAR(255) NULL,
	[First Name] NVARCHAR(255) NULL,
	[Last Name] NVARCHAR(255) NULL,
	[EmailID] NVARCHAR(255) NULL,
	[Phone] NVARCHAR(255) NULL,
	[MobilePhone] NVARCHAR(255) NULL,
	[Payments Terms] NVARCHAR(255) NULL,
	[Contact VAT Treatment] NVARCHAR(255) NULL,
	[Country Code] NVARCHAR(255) NULL,
	[VAT Registration Number] NVARCHAR(255) NULL,
	[Currency Code] NVARCHAR(255) NULL,
	[Notes] NVARCHAR(255) NULL,
	[Website] NVARCHAR(255) NULL,
	[Contact] NVARCHAR(255) NULL,
	[Address ID] NVARCHAR(255) NULL,
	[Billing Address] NVARCHAR(255) NULL,
	[Billing City] NVARCHAR(255) NULL,
	[Billing State] NVARCHAR(255) NULL,
	[Billing Country] NVARCHAR(255) NULL,
	[Billing Code] NVARCHAR(255) NULL,
	[Billing Fax] NVARCHAR(255) NULL,
	[Shipping Address] NVARCHAR(255) NULL,
	[Shipping City] NVARCHAR(255) NULL,
	[Shipping State] NVARCHAR(255) NULL,
	[Shipping Country] NVARCHAR(255) NULL,
	[Shipping Code] NVARCHAR(255) NULL,
	[Shipping Fax] NVARCHAR(255) NULL,
	[CustomField Value1] NVARCHAR(255) NULL,
	[CustomField Value2] NVARCHAR(255) NULL,
	[CustomField Value3] NVARCHAR(255) NULL,
	[CustomField Value4] NVARCHAR(255) NULL,
	[CustomField Value5] NVARCHAR(255) NULL,
	[CustomField Value6] NVARCHAR(255) NULL,
	[CustomField Value7] NVARCHAR(255) NULL,
	[CustomField Value8] NVARCHAR(255) NULL,
	[CustomField Value9] NVARCHAR(255) NULL,
	[CustomField Value10] NVARCHAR(255) NULL
)
